title: Adaptive strategies in historical construction
author:
  name: Pedro Paulo Palazzo
  email: palazzo@unb.br
description: >- # this means to ignore newlines until "baseurl:"
  Emerging order systems in modern construction, from the mid-18th century to
  the mid-20th, as responses to the present-day challenges of sustainability
  and urban resilience.
baseurl: "/adaptive-construction"
url: "https://dmcpatrimonio.github.io"
# The following lines are generally superseded by more specific Minima template
# configurations further below.
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
remote_theme: p3palazzo/minima-scholar
keep_files:
  - reveal.js
header_pages:
  - pibic21-projeto.md

minima:
  date_format : "%e %B %Y"
  social_links:
    twitter   : p3palazzo
    github    : dmcpatrimonio
    instagram : arqtrad

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - kramdown
    # The following plugins are always used by GH-Pages
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links

# Other build parameters
permalink: pretty
markdown: kramdown
kramdown:
  auto_ids: true
  header_offset: 1
  transliterated_header_ids: true
relative_links:
  enabled: true
  collections: true
readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

exclude:
  - .git
  - .github
  - .install
  - .vendor
  - .venv
  - lib
  - spec
  - tmp
